### ISSUE TITLE
Do not open a new tab if the current broswer tab is on a docs page

### ISSUE THREAD

**Issue by sasial-dev** [Sleitnick/rbx-doc-search#2]
The extension should not open a new tab if `window.location` starts with `https://create.roblox.com/docs`. It should instead redirect the current tab. This prevents excessive tab spam.

**Comment by Sleitnick** [comment]
Thanks for opening this issue! A change has been made to not open up a new tab if the current tab is on the documentation site (same URL you listed). The extension with this change has been submitted for review. It will be in version 2.1.2.

**Comment by sasial-dev** [comment]
Thank you for doing it so quickly!
